---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: cartservice
        co.elastic.monitor/hosts: ${data.host}:11000
        co.elastic.monitor/schedule: "@every 5s"
        co.elastic.monitor/timeout: 2s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "checkoutService"
    spec:
      containers:
      - name: cartservice
        image: ctb-cartservice
        readinessProbe:
          tcpSocket:
            port: 11000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: ELASTIC_APM_LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "11000"
        - name: ELASTIC_APM_SERVICE_VERSION
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVICE_VERSION
        - name: ELASTIC_APM_SERVICE_NAME
          value: "cartService"
        - name: ELASTIC_APM_SERVER_URLS
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVER_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  ports:
  - port: 11000
    targetPort: 11000
  selector:
    app: cartservice
