---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: checkoutservice
        co.elastic.monitor/hosts: ${data.host}:8000
        co.elastic.monitor/schedule: "@every 5s"
        co.elastic.monitor/timeout: 2s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "checkoutService"
    spec:
      containers:
      - name: checkoutservice
        image: ctb-checkoutservice
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 500m
           memory: 200Mi
          requests:
           cpu: 50m
           memory: 200Mi
        env:
        - name: PORT
          value: "8000"
        - name: ELASTIC_APM_SERVICE_VERSION
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVICE_VERSION
        - name: ELASTIC_APM_SERVICE_NAME
          value: "checkoutService"
        - name: CART_SERVICE_ADDR
          value: "cartservice:11000"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:9000"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:7000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:6000"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:4000"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:5000"
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVER_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: checkoutservice
