---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  namespace: kube-system
  labels:
    k8s-app: heartbeat
data:
  heartbeat.yml: |-
    setup:
      dashboards:
        enabled: false
      ilm:
        enabled: true
        overwrite: true
        policy_file: /etc/ilm_policy.json
      template:
        enabled: true
        overwrite: true
        settings:
          index:
            number_of_shards: 1
            number_of_replicas: 2
    heartbeat.autodiscover:
      cleanup_timeout: 10s
      providers:
        - type: kubernetes
          hints.enabled: true
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      - add_docker_metadata:
      - if:
          contains:
            cloud.availability_zone: us-central1
        then:
          - add_observer_metadata:
              geo:
                name: gcp-us-central1
                location: 41.2619, -95.8608
        else:
          - if:
              contains:
                cloud.availability_zone: us-east1
            then:
              - add_observer_metadata:
                  geo:
                    name: gcp-us-east1
                    location: 33.1960, -80.0131
            else:
              - add_observer_metadata:
      - drop_fields:
          fields: ["host.name"]
          ignore_missing: true
      - copy_fields:
          fields:
            - from: kubernetes.node.name
              to: host.name
          fail_on_error: false
          ignore_missing: true
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_URL}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      worker: 2
    setup.kibana:
      host: "${KIBANA_URL}"
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
  ilm_policy.json: |-
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_age": "2h",
                "max_size": "20gb"
              }
            }
          },
          "delete": {
            "min_age": "8h",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    k8s-app: heartbeat
    app: beat
spec:
  selector:
    matchLabels:
      k8s-app: heartbeat
  template:
    metadata:
      labels:
        k8s-app: heartbeat
        app: beat
    spec:
      serviceAccountName: heartbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: heartbeat
        image: docker.elastic.co/beats/heartbeat:7.12.0
        imagePullPolicy: Always
        args: [
          "-c", "/etc/heartbeat.yml",
          "-e"
        ]
        env:
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTICSEARCH_URL
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTICSEARCH_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTICSEARCH_PASSWORD
        - name: KIBANA_URL
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: KIBANA_URL
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
        - name: config
          mountPath: /etc/ilm_policy.json
          readOnly: true
          subPath: ilm_policy.json
        - name: dockersock
          mountPath: /var/run
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: heartbeat-config
      - name: dockersock
        hostPath:
          path: /var/run
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    k8s-app: heartbeat
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: heartbeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    k8s-app: heartbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
