---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: productcatalogservice
        co.elastic.monitor/hosts: ${data.host}:9000
        co.elastic.monitor/schedule: "@every 5s"
        co.elastic.monitor/timeout: 2s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "productCatalogService"
    spec:
      containers:
      - name: productcatalogservice
        image: ctb-productcatalogservice
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 200m
           memory: 100Mi
          requests:
           cpu: 50m
           memory: 100Mi
        env:
        - name: PORT
          value: "9000"
        - name: ELASTIC_APM_SERVICE_VERSION
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVICE_VERSION
        - name: ELASTIC_APM_SERVICE_NAME
          value: "productCatalogService"
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVER_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: productcatalogservice
