---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
      annotations:
        co.elastic.monitor/type: tcp
        co.elastic.monitor/name: shippingservice
        co.elastic.monitor/hosts: ${data.host}:7000
        co.elastic.monitor/schedule: "@every 5s"
        co.elastic.monitor/timeout: 2s
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/processors.add_fields.target: "service"
        co.elastic.logs/processors.add_fields.fields.name: "shippingService"
    spec:
      containers:
      - name: shippingservice
        image: ctb-shippingservice
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 100m
           memory: 50Mi
          requests:
           cpu: 15m
           memory: 50Mi
        env:
        - name: PORT
          value: "7000"
        - name: ELASTIC_APM_SERVICE_VERSION
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVICE_VERSION
        - name: ELASTIC_APM_SERVICE_NAME
          value: "shippingService"
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SERVER_URL
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: ctb-secrets
              key: ELASTIC_APM_SECRET_TOKEN
        - name: ELASTIC_APM_ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: shippingservice
