description = 'Ad Service'

group = "adservice"
version = "0.1.0-SNAPSHOT"

buildscript {
    // Define versions here so they are visible inside buildscript.dependencies
    def grpcVersion = "1.17.0"
    def jacksonVersion = "2.9.6"
    def apmVersion = "1.16.0"
    def esVersion = System.getenv('ELASTICSEARCH_VERSION') ?: "9.2.0" // fallback

    repositories {
        mavenCentral()
        mavenLocal()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://artifacts.elastic.co/maven" }
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.3'
        classpath "co.elastic.apm:apm-agent-attach:${apmVersion}"
        classpath "co.elastic.apm:apm-agent-api:${apmVersion}"
        classpath "org.elasticsearch.client:elasticsearch-rest-high-level-client:${esVersion}"
        classpath "org.apache.logging.log4j:log4j-core:2.12.1"
        classpath "co.elastic.logging:log4j2-ecs-layout:0.3.0"
        classpath "org.apache.logging.log4j:log4j-slf4j18-impl:2.12.1"
    }
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'com.google.protobuf'
apply plugin: 'application'

repositories {
    mavenCentral()
    mavenLocal()
    maven { url "https://artifacts.elastic.co/maven" }
}

tasks.withType(JavaCompile) {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

ext {
    speed = project.hasProperty('speed') ? project.getProperty('speed') : false
    offlineCompile = new File("$buildDir/output/lib")
}

dependencies {
    if (speed) {
        implementation fileTree(dir: offlineCompile, include: '*.jar')
    } else {
        implementation "com.google.api.grpc:proto-google-common-protos:1.12.0"
        implementation "io.grpc:grpc-protobuf:1.17.0"
        implementation "io.grpc:grpc-stub:1.17.0"
        implementation "io.grpc:grpc-netty:1.17.0"
        implementation "io.grpc:grpc-services:1.17.0"
        implementation "co.elastic.apm:apm-agent-attach:1.16.0"
        implementation "co.elastic.apm:apm-agent-api:1.16.0"
        implementation "org.elasticsearch.client:elasticsearch-rest-high-level-client:${System.getenv('ELASTICSEARCH_VERSION') ?: '9.2.0'}"
        implementation "co.elastic.logging:log4j2-ecs-layout:0.3.0"
        implementation "org.apache.logging.log4j:log4j-slf4j18-impl:2.12.1"
        implementation "org.apache.logging.log4j:log4j-core:2.12.1"

        runtimeOnly "com.fasterxml.jackson.core:jackson-core:2.9.6"
        runtimeOnly "com.fasterxml.jackson.core:jackson-databind:2.9.6"
        runtimeOnly "io.netty:netty-tcnative-boringssl-static:2.0.8.Final"
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.5.1-1'
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.17.0"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
        ofSourceSet('main')
    }
}

sourceSets {
    main {
        java {
            srcDirs 'hipstershop'
            srcDirs 'build/generated/source/proto/main/java/hipstershop'
            srcDirs 'build/generated/source/proto/main/grpc/hipstershop'
        }
    }
}

startScripts.enabled = false

task downloadRepos(type: Copy) {
    from configurations.compileClasspath
    into offlineCompile
    from configurations.runtimeClasspath
    into offlineCompile
}

task adService(type: CreateStartScripts) {
    mainClassName = 'hipstershop.AdService'
    applicationName = 'AdService'
    outputDir = new File(project.buildDir, 'tmp')
    classpath = jar.outputs.files + project.configurations.runtimeClasspath
}

task adServiceClient(type: CreateStartScripts) {
    mainClassName = 'hipstershop.AdServiceClient'
    applicationName = 'AdServiceClient'
    outputDir = new File(project.buildDir, 'tmp')
    classpath = jar.outputs.files + project.configurations.runtimeClasspath
}

applicationDistribution.into('bin') {
    from(adService)
    from(adServiceClient)
    fileMode = 0755
}
